### ISSUE TITLE
Unable to disable support for  rds , dccp , sctp ,  ticp protocol

### ISSUE THREAD

**Issue by evil-user** [TommyTran732/Arch-Setup-Script#14]
I used lynis 3.0.8 it suggests me to disable support for rds , dccp , sctp , ticp  protocol if not  required though this installer script should have disabled these protocols. I am using linux-hardened kernel 5.17.15

**Comment by evil-user** [comment]
@tommytran732 should i post lynis logs here. I don't know how to report log securely :(

**Comment by tommytran732** [comment]
You can email me or contact me on Matrix. The details are at https://tommytran.io/#contact

**Comment by TommyTran732** [comment]
Should be blocked by default with this: https://github.com/TommyTran732/Arch-Setup-Script/blob/dee25eae388203f51641d774ec4287490deae1c7/install.sh#L359
