### ISSUE TITLE
can't boot up to the linux kernel

### ISSUE THREAD

**Issue by howtofixthis** [TommyTran732/Arch-Setup-Script#22]
when the installation is allegedly completed, I get this screen, apparently my PC can't locate the linux kernel. I know that the problem must occur somewhere in the BTRFS mounting/formating/subvolumes but I couldn't find the error message from the outputs, I tried every command line by line so the procedure or the order of installing it must be somehow unfinished or wrong because I can't boot up to the OS.
![image](https://user-images.githubusercontent.com/122227457/211211987-0868647f-e738-4788-8cbd-665dd75fd809.png)

**Comment by TommyTran732** [comment]
Sorry for the late reply, I have just come back to Arch. Anyhow, it should be fixed now.
