### ISSUE TITLE
the script can't find: "gnome-software-packagekit-plugin"

### ISSUE THREAD

**Issue by xe-3** [TommyTran732/Arch-Setup-Script#24]
**Describe the bug**
installation fails because the installer cannot find `gnome-software-packagekit-plugin`

**To Reproduce**
1. Run the desktop.sh script per the instructions in the readme
2. "Proceed with the installation"
3. Error occurs during installation

The error:
 `error: target not found: gnome-software-packagekit-plugin`
`ERROR: Failed to install packages to new root`

**Additional context**
I checked the Arch Repositories and there is no package in the repos named "gnome-software-packagekit-plugin"

I do see that there is an AUR package called "gnome-software-packagekit-plugin.git"

**Comment by xe-3** [comment]
Update 2:
Removing `gnome-software-packagekit-plugin` from line 216 (the pacstrap step) resolves this problem. But I believe this means gnome-software will have no integration with packagekit

**Comment by TommyTran732** [comment]
I will remove gnome-software
