### ISSUE TITLE
Dropped to emergency shell after reboot

### ISSUE THREAD

**Issue by 5ouls3dge** [TommyTran732/Arch-Setup-Script#26]
**Describe the bug**
Waiting 10 seconds for device /dev/mapper/cryptroot ...
ERROR: device '/dev/mapper/cryptroot' not found. Skipping fsck.
:: mounting 'dev/mapper/cryptroot' on real root
mount:/new_root: no valid filesystem type specified.
ERROR: Failed to mount '/dev/mapper/cryptroot' on real root

**To Reproduce**
install server.sh reboot after the script runs. no additional steps done. straight reboot

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mihneaCR** [comment]
I am experiencing this exact issue also.

**Comment by 5ouls3dge** [comment]
Wow thank you, thought i was alone, rewritting the script to find it. what do you think of this line. No system to test code if you have a vm see if it makes a difference? 


`# Formatting the LUKS Container as BTRFS.
echo "Formatting the LUKS container as BTRFS."
mkfs.btrfs $BTRFS &>/dev/null
#this line:
mount -o clear_cache,nospace_cache $BTRFS $MOUNT_POINT

# Change to ..... Create and set COW on the Btrfs subvolumes
mount -t btrfs $BTRFS $MOUNT_POINT
`

The code is well written. hard to find bug. i have created a version that removes the crypt file part to see if it resolves it. to see if it is isolated around that setup.

**Comment by mihneaCR** [comment]
I don't think that this will change anything, the error stems from grub (I think) not being able to find /dev/mapper/cryptroot, which occurs one step prior to the mount call. /dev/mapper/cryptroot is the device then being mounted by the call you mention, it does not appear in the emergency shell, thus indicating a problem with the encryption.

**Comment by 5ouls3dge** [comment]
I cant test, but i think this is the error, comma missed in the replace action?:

sed -i 's#FILES=()#FILES=(/cryptkey/.root.key)#g' /mnt/etc/mkinitcpio.conf

to

sed -i 's#FILES=(),#FILES=(/cryptkey/.root.key)#g' /mnt/etc/mkinitcpio.conf

**Comment by 5ouls3dge** [comment]
@TommyTran732 does the script work for you? Any ideas on this?
