### ISSUE TITLE
interesting :)

### ISSUE THREAD

**Issue by kronikpillow** [TommyTran732/Arch-Setup-Script#32]
Interesting ... I'v been working on something similar, and have achieved same result ... athou i haven't taken a detailed look at your installer yet, i'm wondering ... is there any valid reason to not exclude entire /var from snapshots except the pacman database? which is on my setup mitigated by moving DBPath to /usr/lib/pacman from /var/lib/pacman ... in my current running setup, everything seems to work so far without any issues ... 

Grub-btrfs with the grub-btrfs-overlay-fs flag allows you to boot with a read-only snapshot, totally eliminating the breaking up of /var ... unless, there is something else im not aware off? 

https://github.com/kronikpillow/arch-install ...

also, another difference seems to be that yours is self-automated ,mine has manual steps as i haven't learned yet that kind of shell scripting :)

**Comment by TommyTran732** [comment]
> is there any valid reason to not exclude entire /var from snapshots except the pacman database?

I am not sure if this is the best approach, even if the pacman database can be moved (and I am not sure if my approach is the best either). Say you did a global Flatpak install of an app, which will install it into /var, do you expect it to rollback with the rest of the system?

`grub-btrfs-overlay-fs` seems to be nicer than set up than what I have currently. I might switch to using it if it works nicely with snapper. Did you test it with snapper rollback and stuff?

**Comment by TommyTran732** [comment]
I have decided to not implement overlayfs. The reasons behind this are:
- It may lead to confusion as you forget that you are booting into a readonly snapshot, especially if you are multitasking and whatnot.
- This is not openSUSE's behavior, afaik.
