### ISSUE TITLE
Unbound Configuration 404?

### ISSUE THREAD

**Issue by funk-on-code** [TommyTran732/Arch-Setup-Script#40]
Stock server install pulls a **/etc/unbound/unbound.conf** that contains:

`404: Not Found`

I think, line 499:

`https://raw.githubusercontent.com/TommyTran732/Linux-Setup-Scripts/main/etc/unbound/unbound.conf`

should actually be:

`https://raw.githubusercontent.com/TommyTran732/Arch-Setup-Script/main/etc/unbound/unbound.conf`

which provides the file as intended.

**Comment by TommyTran732** [comment]
Fixed in https://github.com/TommyTran732/Arch-Setup-Script/commit/a68405a23a7c9db3203407ec983e2667a0541a1b, thank you for the report.
