### ISSUE TITLE
Should unbound echo itself to resolv.conf?

### ISSUE THREAD

**Issue by funk-on-code** [TommyTran732/Arch-Setup-Script#47]
Once unbound is installed as the DNS/Resolver, should the script not do something like:

`echo 127.0.0.1 >> /etc/resolv.conf`

to use it?

Otherwise, if #45 is merged and/or a better solution is found, the server option boots cleanly in both VMs and bare-metal.

**Comment by TommyTran732** [comment]
Doesn't it already do it by itself? I will check later

**Comment by TommyTran732** [comment]
Okay I just checked. Unbound doesn't need to echo itself into /etc/resolv.conf. If /etc/resolv.conf doesn't have a nameserver and unbound is present, the system defaults to using unbound. You can check this with dig.

Let me know if you still think it should be added for some reason though.
