### ISSUE TITLE
Rebooting for the first time after a vm installation on qemu does not boot

### ISSUE THREAD

**Issue by antonispgs** [TommyTran732/Arch-Setup-Script#49]
The installation finishes seemingly successfully, then this happens with no way to go around it. I did not select LUKS during the installation and the type is desktop. (see picture attached)
Tried with the most recent ISO and the one from August.
![image](https://github.com/user-attachments/assets/7705a94a-ce50-4822-a9e2-89d99b0fd8b9)

**Comment by TommyTran732** [comment]
Resolved in Matrix. SeaBIOS is not supported.
