### ISSUE TITLE
Install without Desktop environment

### ISSUE THREAD

**Issue by one618** [TommyTran732/Arch-Setup-Script#6]
Hello there,
is it possible to install just the base system without a desktop environment ? since i want to use dwm
or I'm forced to use gnome  with this script?

**Comment by tommytran732** [comment]
Sorry for the late reply, I have been busy. I can work on something like this in the future.

**Comment by TommyTran732** [comment]
Closing this since I do not have any plan to support anything but GNOME and headless server.
