### ISSUE TITLE
Doubt Regarding Apparmor enabled using this script

### ISSUE THREAD

**Issue by Anish-M-code** [tommytran732/Arch-Setup-Script#8]
@tommytran732  @AryunGupta @ajeyrgowda Total newbie here , I read the install.sh code but i wonder if i have to create apparmor profiles for each and every application i install in arch. Is there any advantage if we enable apparmor but don't use apparmor profiles.

**Comment by tommytran732** [comment]
There are basic profiles that come with just having apparmor it, though for it to really be effective you need to make your own profiles.

**Comment by Anish-M-code** [comment]
Thank you
