### ISSUE TITLE
Broken link for IO udev rules used in Arch setup script

### ISSUE THREAD

**Issue by Anish-M-code** [tommytran732/Arch-Setup-Script#9]
Hi @tommytran732 , the link used for IO udev rules seems to be broken. The following link throws error.
https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-common-settings/-/tree/master/etc/udev/rules.d

**Comment by tommytran732** [comment]
Oh dear, they moved it. I will checj whats up with this later. For now you can just comment out those lines.

**Comment by tommytran732** [comment]
I will just remove it from the script
